# Generated by Django 5.0 on 2025-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_tonnage_project_vintage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hedera_token_id',
        ),
        migrations.AddField(
            model_name='project',
            name='projectId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
