# Generated by Django 5.0 on 2025-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_hedera_token_id_project_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
