# Generated by Django 5.0 on 2025-10-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_projectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectId',
            new_name='hedera_token_id',
        ),
    ]
