# Generated by Django 5.0 on 2025-10-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_projectid_project_hedera_token_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hedera_token_id',
            new_name='projectId',
        ),
    ]
