# Generated by Django 5.0 on 2025-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
