# Generated by Django 5.0 on 2025-10-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_listing_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='metadata_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
