# Generated by Django 5.0 on 2025-10-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hedera_private_key',
        ),
    ]
