# Generated by Django 5.0 on 2025-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_hedera_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('VERIFIER', 'Verifier'), ('ADMIN', 'Admin')], default='BUYER', max_length=10),
        ),
    ]
